server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_bookstore?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: localhost
    port: 6379
    #Client name to be set on connections with CLIENT SETNAME.
    clientName: ""
    password: ""
    timeout: 5000

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: bookstore-secret-key
  expiration: 86400000  # 1 天

logging:
  level:
    com.bookstore: DEBUG # 设置日志级别